### PR TITLE
Improve self-reference workaround (fixes #180)

### LINKED ISSUE #180: Failing to generate import in certain situations
## Description of issue
I have some issues with certain files not importing schemas before using them.

## Dependencies
- prisma 5.1.0
- zod-prisma-types 2.7.9
## Code
I have the following schema:
```prisma
generator zod {
  provider                  = "zod-prisma-types"
  output                    = "./generated/schemas" // default is ./generated/zod
  useMultipleFiles          = true // default is false
  createModelTypes          = false // default is true
  createRelationValuesTypes = true // default is false
}

/// @@Gen.model(hide: true)
model Role {
  id        String    @id @default(uuid())
  createdAt DateTime  @default(now())
  updatedAt DateTime? @updatedAt
  deletedAt DateTime?

  PermissionForRole PermissionForRole[]
}

/// @@Gen.model(hide: true)
model PermissionForRole {
  id        String    @id @default(uuid())
  createdAt DateTime  @default(now())
  updatedAt DateTime  @updatedAt
  deletedAt DateTime?

  roleId String
  role   Role   @relation(fields: [roleId], references: [id])

  @@unique([roleId])
}
```

This full reproduction repo can be found at https://github.com/datagutt/prisma-zod-bug.
## Current behaviour
In generated/schemas/outputTypeSchemas/RoleFindManyArgsSchema.ts, this line fails:
```typescript

  PermissionForRole: z.union([z.boolean(),z.lazy(() => PermissionForRoleFindManyArgsSchema)]).optional(),
```
This is due to ``PermissionForRoleFindManyArgsSchema`` never being imported. This seems to only be happening in the ``RoleFindManyArgsSchema.ts``-file, not other files.

## Expected behaviour
``PermissionForRoleFindManyArgsSchema`` should be imported in the files that use it.

## Additional information
It seems that this bug is not triggered if the two models are named something completely different. I think the bug is related to both models starting or ending with "Role". Renaming ``PermissionForRole``to something different causes the file to be correctly imported.

### PR DESCRIPTION
**Pull request by datagutt**
Hi,
I recently found an issue (https://github.com/chrishoermann/zod-prisma-types/issues/180) where certain files were missing imports.
I managed to create a quick fix for this.

### CODE REVIEW

**Comment by nbibler** [comment]
I'm seeing the same issue in an application and this PR does look to correct the problem. 👍

**Review by chrishoermann — APPROVED** [review]
Thanks for the fix.

**Comment by chrishoermann** [comment]
This should be working in 2.7.10 now. Can you please check on your end?

**Comment by nbibler** [comment]
LGTM. 👍

**Pull request merged**
